version: '3.8'

services:
  postgres:
    build:
      context: ./db-setup
    container_name: Postgres-employees-performance-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_MONITOR_USER=${POSTGRES_MONITOR_USER}
      - POSTGRES_MONITOR_PASSWORD=${POSTGRES_MONITOR_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-setup/configs:/etc/postgresql:ro
      - ./db-setup/logs:/var/log/postgresql:rw
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      app-network:
        aliases:
          - postgres-newrelic
    restart: unless-stopped

  api:
    build: ./api
    container_name: Postgres-employees-api
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres-newrelic:5432/${POSTGRES_DB}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}-API
      - PORT=${API_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "${API_PORT:-3000}:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      app-network:
        aliases:
          - api-layer
    restart: unless-stopped

  k6:
    build: ./k6
    container_name: Postgres-employees-load-gen
    environment:
      - API_URL=http://api-layer:3000
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}-LoadGen
      - K6_VUS=${K6_VUS:-50}
      - K6_DURATION=${K6_DURATION:-30m}
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network
    restart: "no"

  newrelic-infra-bundle:
    build:
      context: ./infrastructure/newrelic
      dockerfile: Dockerfile
      args:
        - POSTGRES_INTEGRATION_BRANCH=${POSTGRES_INTEGRATION_BRANCH:-main}
    container_name: Postgres-employees-newrelic-monitoring
    cap_add:
      - SYS_PTRACE
    privileged: true
    pid: host
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infrastructure/newrelic/integrations.d/:/etc/newrelic-infra/integrations.d/:ro
    environment:
      - NRIA_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NRIA_DISPLAY_NAME=${NRIA_DISPLAY_NAME}
      - NRIA_VERBOSE=1
      - NRIA_CUSTOM_ATTRIBUTES={"environment":"${NODE_ENV:-production}"}
      - NR_POSTGRES_USERNAME=${POSTGRES_MONITOR_USER}
      - NR_POSTGRES_PASSWORD=${POSTGRES_MONITOR_PASSWORD}
      - NR_POSTGRES_HOSTNAME=postgres-newrelic
      - NR_POSTGRES_PORT=5432
      - NR_POSTGRES_DATABASE=${POSTGRES_DB}
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/newrelic-infra", "agent", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  postgres_data:
