custom_metrics:
  - query: |
      SELECT COUNT(*) as current_salaries
      FROM salaries 
      WHERE to_date = '9999-01-01'
    interval: 60

  - query: |
      SELECT COUNT(*) as active_departments
      FROM dept_emp 
      WHERE to_date = '9999-01-01'
    interval: 60
