USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'${MSSQL_MONITOR_USER}')
BEGIN
    CREATE LOGIN [${MSSQL_MONITOR_USER}] WITH PASSWORD = N'${MSSQL_MONITOR_PASSWORD}';
END;
GO

USE [employees];
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'${MSSQL_MONITOR_USER}')
BEGIN
    CREATE USER [${MSSQL_MONITOR_USER}] FOR LOGIN [${MSSQL_MONITOR_USER}];
    GRANT VIEW DATABASE STATE TO [${MSSQL_MONITOR_USER}];
    GRANT SELECT ON OBJECT::sys.dm_exec_query_stats TO [${MSSQL_MONITOR_USER}];
END;
GO

-- Enable Query Store for performance metrics
ALTER DATABASE CURRENT SET QUERY_STORE = ON;
ALTER DATABASE CURRENT SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30));
GO
