integrations:
  - name: nri-mysql
    interval: 15s
    command: all_data
    env:
      HOSTNAME: ${MYSQL_HOST}
      PORT: ${MYSQL_PORT}
      USERNAME: ${MYSQL_MONITOR_USER}
      PASSWORD: ${MYSQL_MONITOR_PASSWORD}
      REMOTE_MONITORING: true
      EXTENDED_METRICS: true
      EXTENDED_INNODB_METRICS: true
      EXTENDED_PERFORMANCE_METRICS: true
      TABLES_METRICS: true
    
    config:
      slow_query_metrics: true
      query_response_time_stats: true
      
      innodb_metrics:
        buffer_pool_metrics: true
        lock_metrics: true
        page_metrics: true
        
      table_metrics:
        size_metrics: true
        index_metrics: true
        
      tables:
        - employees
        - departments
        - dept_emp
        - salaries
